### PR TITLE
feat: add custom transform

### PR DESCRIPTION
**Pull request by fsdiogo**
This PR adds the ability to customise transforms to be used to relocate the dropdown.

It will be used in https://github.com/ipfs-shipyard/ipfs-webui/pull/929.

/cc @olizilla

### CODE REVIEW

**Comment by fsdiogo** [comment]
Done!

transforms

Also switched from `babel-preset-react` to `@babel/preset-react` because it was breaking the examples.

**Comment by fsdiogo** [comment]
Sorry, missed the `babel-cli` => `@babel/cli`. It should be working now!

**Comment by olizilla** [comment]
almost... perhaps the lib dir needs to exist first?

```console
> @tableflip/react-dropdown@1.1.1 build:js /Users/oli/Code/tableflip/react-dropdown
> babel src/index.js -o lib/index.js

{ Error: ENOENT: no such file or directory, open 'lib/index.js'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1168:35)
    at output (/Users/oli/Code/tableflip/react-dropdown/node_modules/@babel/cli/lib/babel/file.js:148:23)
    at /Users/oli/Code/tableflip/react-dropdown/node_modules/@babel/cli/lib/babel/file.js:234:9
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/oli/Code/tableflip/react-dropdown/node_modules/@babel/cli/lib/babel/file.js:74:103)
    at _next (/Users/oli/Code/tableflip/react-dropdown/node_modules/@babel/cli/lib/babel/file.js:76:194)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'lib/index.js' }
```

**Comment by fsdiogo** [comment]
Yeah, the folder had to exist.

Now using the `-d` option that creates the folder if it doesn't exist.

**Pull request merged**
